name: Build TeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          run: |
            cd doc
            tlmgr install arara
            arara luxmetr.tex
